### ISSUE TITLE
create uninstall form

### ISSUE THREAD

**Issue by screberg** [precision-sustainable-ag/Kobo#14]
Uninstall form.  Used for switching out equipment that is broken or taking equipment out in the fall.  Have to scan everything to uninstall and install.

**Comment by saseehav** [comment]
https://github.com/precision-sustainable-ag/Kobo/commit/65aae39a3ac2d4092592e32336bf19f9d77e8477#commitcomment-39580792

**Comment by saseehav** [comment]
uninstall form merged into main branch
