### ISSUE TITLE
versioning and diffs

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/Kobo#4]
as of today: 
all useful files for Kobo will still be stored as XLSX and imported into Kobo this way.

Diffs for parsing purposes: looks like CSV are easier to do diffs on.  
XLSX can be converted to .ZIP and XML files opened, but the process is trickier than csv conversions and xml diffs still not easy to read.

**Comment by screberg** [comment]
Final solution was to export csv into their own folder to see diffs and use as xlsx as the version released
