### ISSUE TITLE
Link Kobo forms to Git Issues

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/Kobo#9]
We have a form called psa_water_sensor_install
The last question is "Do you have any issues to report?"
Link the response to this question somehow to log issues in GitHub

**Comment by saseehav** [comment]
Did we decide that each 'thing' (ie: sensors, forms, biomass, etc) that has a repo gets the Issues? Or are we just dumping all "Issues" logged inside forms into the On-Farm Protocols Repo? Is that why it was created?

**Comment by screberg** [comment]
I think you nailed it.  We created the on-farm protocols repo just for issues logging.  Sounds like it also serves now to house the final versions of protocols as they are released each year.  I think I'll update the ReadMe now to reflect that.

**Comment by saseehav** [comment]
This issue is to link a response from the webhook inside a Kobo form to log an issue in GitHub.  We still need to solve that, especially for logging sensor issues in the sensor repo.  What Repo do you want Sensor issues logged?

**Comment by saseehav** [comment]
I still love the idea of writing, 'do you have an issue' at the end of every form that gets logged into the database for record keeping, to view in the dashboard, for the data shepherd to see, etc. We were going to also direct this from the database into GitHub to be tagged in different people's repos for dealing with issues.  Is this something we still have on the horizon for troubleshooting next year?

**Comment by screberg** [comment]
Agreed with all of last comment.  These goals were recently captured in the API dash and are tagged to occur this fall
